[package]
name = "aptos-project"
version = "1.0.0"
authors = []

[addresses]
HelloMessage = "0x2c049b5fba289f6e362047e213eba250fcf6307266cbebcfc65fd9aa39ed8406"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]